name: Tests

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        tuleap_functions:
          - "artifact-post-action/auto-assign"
          - "artifact-post-action/compute-risk"
          - "artifact-post-action/post-action-add-comment"
    runs-on: ubuntu-22.04
    name: Tests (${{ matrix.tuleap_functions }})
    defaults:
      run:
        working-directory: ${{ matrix.tuleap_functions }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
      - name: Prepare
        run: nix-shell --run "make prepare"
      - name: Tests
        run: nix-shell --pure --run "make tests"
      - name: Build
        run: nix-shell --pure --run "make build"
